name: Build and Push and Run PythonImage

on:
  workflow_dispatch:
    inputs:
      dockerimage-name:
          description: 'Docker Image Name '
          required: true
          type: string
      enviornment:
          description: 'App Env '
          required: true
          type: choice
          options: 
          - production
          - development
          - staging

      

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            FLASK_ENV=${{inputs.enviornment}}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{inputs.dockerimage-name}}:latest
  
      - name: Docker Buildx Pull and Build
        uses: djbender/docker-buildx-pull-or-build@v0.3
        with:
            docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
            docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            docker_registry: ${{ inputs.docker-registry }}
            image: ${{ secrets.DOCKER_HUB_USERNAME }}/${{inputs.dockerimage-name}}_new
      - name: Run Docker Container 
        uses: addnab/docker-run-action@v3
        with:
          image: ${{inputs.dockerimage-name}}
          run: echo "hello Flask jan"